export const COLORS = {
	// Brand colors
	BRAND_PRIMARY: "#A47864",
	BRAND_DARK: "#604538",
	BRAND_LIGHT: "#FCE2C2",
	BRAND_SECONDARY: "#C6AB9E",
	BRAND_TERTIARY: "#A17866",
	BRAND_QUATERNARY: "#7A4B3A",

	// UI colors
	INACTIVE: "#989898",
	TEXT_LIGHT: "#E8E2D9",
	TEXT_PRIMARY: "#213547",
	BACKGROUND_LIGHT: "#F5F0E8",
	BACKGROUND_MEDIUM: "#E0D9CF",

	// State colors
	SUCCESS: "green",
	ERROR: "red",
	WARNING: "orange",
	INFO: "blue",
};
