export const ROUTES = {
	HOME: "/",
	PRODUCTS: "/products",
	ABOUT: "/about",
	SIGNUP: "/signup",
	LOGIN: "/login",
	NOT_FOUND: "*",
	CUSTOM: "/custom",
	CUSTOM_PAGE1: "/custom/page1",
	CUSTOM_PAGE2: "/custom/page2",
	CUSTOM_PAGE3: "/custom/page3",
	CUSTOM_PAGE4: "/custom/page4",
	CUSTOM_PAGE5: "/custom/page5",
	ADMIN_DASHBOARD: "/admin/dashboard",
	CHECKOUT: "/checkout",
};
