openapi: 3.0.3
info:
  title: Chocolate Customizer API
  description: API for the chocolate customization service
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /chocolate/types:
    get:
      summary: Get all chocolate types
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChocolateType'
  /chocolate/toppings:
    get:
      summary: Get all available toppings
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topping'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        imageUrl:
          type: string
          format: uri
    ChocolateType:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        priceMultiplier:
          type: number
          format: float
    Topping:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        category:
          type: string